### ISSUE TITLE
Server Crash With Last AE2

### ISSUE THREAD

**Issue by TheLimePixel** [MrDj200/SpatialComapt#3]
A crash occurs when using the mod together with AE2 stable 8:
https://pastebin.com/6VmjTYT4

**Comment by MrDj200** [comment]
Jup, saw that, already looking into it.

Did you add a new mod before it started to crash, or was it just the ae2 update?

-Dj

**Comment by TheLimePixel** [comment]
Yeah, it seems that it wasn't the AE2 update as when I go back to stable 7 it doesn't occur. I've just updated Forestry, EvilCraft, CyclopsCore, Integrated Dynamics, Game Stages, B.A.S.E., Wireless Crafting Terminal and Enderman Evolution

**Comment by MrDj200** [comment]
As I had this earlier with my modpack when I updatet, I'll check which mods I updatet, and find the error and fix it ASAP. Sry for the trouble ^^

-Dj

**Comment by MrDj200** [comment]
My Recommendation: Deactivate the mod for now.
I can't find the faulty mod, and the AE2 Dev seems to be removing that functionality anyways
 (at least that's what I understood from this:  [CLICK ME](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3377))

If I find a way to make it work again, I'll answer on this issue again!

-Dj
