### ISSUE TITLE
Server Crash with Ae2-Rv5-Stable11 

### ISSUE THREAD

**Issue by lays24mc** [MrDj200/SpatialComapt#4]
Game crashed when I used SpatialCompat with AE2-Rev5-Stable11. When I disabled Spatial Compat it works fine.

Crashlog: https://pastebin.com/r6EjkUnL

Forge: 1.12.2-2751
AE2 Rv5 Stable 11
Spatial Compat 1.12.2 - 1.3

**Comment by MrDj200** [comment]
Sorry for the late answer. 
If you could provide the log, I can maybe find the error.

**Comment by lays24mc** [comment]
EDIT: The problem is in an other Mod. I close the Issue ;)

Here the crashlog: https://pastebin.com/r6EjkUnL

And here a short debug.log before it crashed: https://pastebin.com/Haf5Md1c
