### ISSUE TITLE
Mod conflict with Applied Integrations

### ISSUE THREAD

**Issue by indiscrete-void** [MrDj200/SpatialComapt#5]
Hello, i'm a developer of applied integrations, 8 days ago i received this issue on my issue tracker on github: https://github.com/AzazeII/Applied-Integrations/issues/13

Milii20's server is crashing when both applied integrations and spatial compat is installed, there is latest crash-log:
https://pastebin.com/fMPWub1e

How can we fix this issue?

**Comment by indiscrete-void** [comment]
After some debug, i can say what class is causing problem, there is it: https://github.com/AzazeII/Applied-Integrations/blob/1.12.2/src/main/java/AppliedIntegrations/tile/LogicBus/TileLogicBusCore.java

But i still have no idea what is causing this crash to happen

**Comment by indiscrete-void** [comment]
Seams like issue is only caused by my mod, closing it

**Comment by MrDj200** [comment]
If you cant figure out a way to fix it on your end, I think I can fix it on my end. 
Just let me know when you can't fix it.

-Dj

**Comment by indiscrete-void** [comment]
I fixed this issue, it was caused by two tile entities.
TileBlackHole 
    Method: "pullEntities(EntityPlayer p)", which was trying to pull client entities on server

TileLogicBusCore
    Method: "writeNbt(NBTTag tag"), which was trying to write client world on server
