### ISSUE TITLE
Server Crashes with AE2: appliedenergistics2-rv6-stable-7

### ISSUE THREAD

**Issue by Crimson3076** [MrDj200/SpatialComapt#7]
[crash-2020-12-09_21.33.44-server.txt](https://github.com/MrDj200/SpatialComapt/files/5670033/crash-2020-12-09_21.33.44-server.txt)

**Comment by MrDj200** [comment]
Does it crash when you start the server, or when you use spatial storage?

**Comment by Crimson3076** [comment]
It crashes when I use spatial storage and start the server, the server can't start at all

**Comment by MrDj200** [comment]
- Does it still crash without spatial compat installed?
> If yes:
>> This needs to be reported to Applied Energistcs Issue tracker

> If no:
>> what block/entity did you put inside the spatial storage?

**Comment by Crimson3076** [comment]
the server or game wouldn't start at all, wasn't able to test if the blocks were compatible

**Comment by MrDj200** [comment]
But you said it crashed when you used spatial storage? How did you use it when the server doesnt start?

**Comment by Crimson3076** [comment]
the server doesn't start when it's installed* 
sorry for the confusion

**Comment by MrDj200** [comment]
interesting.
could you send a link to your modpack?
I need to test some things to determine what's causing the problem

**Comment by Crimson3076** [comment]
Sure thing, the modpack is on technic launcher

https://www.technicpack.net/modpack/crimsons-modpack.1774630

**Comment by MrDj200** [comment]
sorry, I don't support the technic launcher.
The last time I logged into it was shortly before I lost my old minecraft account, and I can't download the modpack without logging in.
A friend of mine tested your pack, but it crashed for other reasons than my mod (namely astral sorcery and forestry after that).

If your server really only crashes with my mod installed (spatialservermod-1.3.jar), then it's most certainly 1 mod not linking what I'm doing (which makes no sense with the way I'm doing things).
In that case you should narrow down which mod that is (removing mods until it works/adding mods until it no longer works), then I can help you.

IF you still get the same crash after removing my mod (spatialservermod-1.3.jar), report it to AE2.
