### ISSUE TITLE
Server Crash on Startup with Galacticraft, IC2 Classic, AE2 and SpatialCompat

### ISSUE THREAD

**Issue by TGWaffles** [MrDj200/SpatialComapt#8]
I got this error ([crash-2021-04-08_03.46.26-server.txt](https://github.com/MrDj200/SpatialComapt/files/6275895/crash-2021-04-08_03.46.26-server.txt)) in my test modpack (unreleased) and stripped down the modpack to isolate the offenders. 

The minimum reproducible mods to cause this are:

- appliedenergistics2 | rv6-stable-7
- spatialservermod    | 1.3 
- micdoodlecore
- galacticraftcore    | 4.0.2.280 (requires micdoodlecore)
- IC2Classic            | 1.5.4.5

Unsure if versions matter, left them in anyway in case a previous/later version works fine.

The error is reproducible and causes a server crash before the world is loaded etc. No need to place any blocks to cause this crash. Can even have a blank world.

Removing SpatialCompat fixes the error. These mods work together fine without SpatialCompat, but adding this mod causes a crash.

The error appears to be in line 44 of IMCSpatial.java

-Thomas

**Comment by MrDj200** [comment]
Closed with 1.3.1
