### ISSUE TITLE
Crash when launch the modpack without Buildcraft

### ISSUE THREAD

**Issue by magcicada** [MrDj200/SpatialComapt#9]
https://paste.dimdev.org/opizogiqot.mccrash

**Comment by magcicada** [comment]
`Caused by: java.lang.NoClassDefFoundError: buildcraft/api/mj/IMjConnector`

**Comment by MrDj200** [comment]
I can start without buildcraft just fine. Can you give me a link to the modpack so I can test better?

**Comment by magcicada** [comment]
This is my own modpack,it is not posted on curseforge.

**Comment by magcicada** [comment]
It may be the result of it with other mods,ExtraCells2,AE2 stuff or Wireless Crafting Terminal,but the CR report that `at appeng.core.api.imc.IMCSpatial.process(IMCSpatial.java:44)`,So I think this issiue should be resolved in SpatialComapt.

**Comment by magcicada** [comment]
AE2 stuff is our own compiled version, ExtraCells2 is a fork version.

[ae2stuff and extracells2.zip](https://github.com/MrDj200/SpatialComapt/files/6624284/ae2stuff.and.extracells2.zip)

**Comment by MrDj200** [comment]
When you remove my mod, does it still crash?

Because `IMCSpatial.java` is a class from Applied Energistics

**Comment by magcicada** [comment]
no,remove SpatialComapt it start well.

**Comment by MrDj200** [comment]
Can you send the latest log when it crashes?

**Comment by magcicada** [comment]
[Uploading 2021-06-09-4.log.gz…]()

**Comment by magcicada** [comment]
I'm not sure if it is this one，the file is too messy...

**Comment by magcicada** [comment]
[2021-06-09-3.log.gz](https://github.com/MrDj200/SpatialComapt/files/6624418/2021-06-09-3.log.gz)
I think it is this one,sorry for the wrong file.

**Comment by magcicada** [comment]
If this crash contains `Mixins`, it may also be a crash caused by the mod MixinBooter. No tested, not sure that.

**Comment by MrDj200** [comment]
Could you send the complete modpack?
I need it to diagnose this issue

**Comment by magcicada** [comment]
[mods](https://www.dropbox.com/sh/cih6ma7ij38rhg6/AAADV6I6MYvf3RLkHPbW3h8Xa?dl=0)
[config](https://www.dropbox.com/sh/cih6ma7ij38rhg6/AAADV6I6MYvf3RLkHPbW3h8Xa?dl=0)

**Comment by MrDj200** [comment]
you posted the same link twice
I only got the mods

**Comment by magcicada** [comment]
[config](https://www.dropbox.com/sh/fnp8sjcygrjz33b/AAAhO9K1Tgelm6DblekL1d2Va?dl=0)

**Comment by magcicada** [comment]
I have deleted SpatialComapt in mods file.

**Comment by ErnestoPeroPezzi** [comment]
Was there any followup to this? I am getting the same crash.

https://pastebin.com/RE4PxZiC

**Comment by MrDj200** [comment]
I never figured it out to be honest.
The fixes I tried never worked, especially since I'm unable to reproduce this error at all.

If you can, try to get it reproduced with the least amount of mods possible.
I'm not sure if this is a hardware issue, windows version things or something else.
I was able to start the modpack that was sent here without issues.

**Comment by ErnestoPeroPezzi** [comment]
I am going to assume it has something to do with the way you add compatibility to buildcraft? I got around the crash by adding buildcraft (and disabling everything in it since I dont need it).

If anything, as a workaround, you could push a build that removes anything explicitly referencing buildcraft and hopefully that should work?

**Comment by MrDj200** [comment]
I shouldn't have any references to buildcraft in my code.
Unable to check right now, but if memory serves me right, the only mod I'm referencing directly should be Funky Locomotion to disable their stuff in spatial storage.

**Comment by ErnestoPeroPezzi** [comment]
Alright sounds good. Thanks for maintaining support at least, much appreciated. Putting in Buildcraft Core  [https://www.curseforge.com/minecraft/mc-mods/buildcraft-core](url) lets me run it without the bloat of Buildcraft, so I guess its a decent workaround.

Thanks again and cheers

**Comment by MrDj200** [comment]
Okay, it's good you found a workaround.
